<a href="https://colab.research.google.com/github/audrb1999/ML-DL-Study/blob/main/%EB%B0%91%EB%94%A51/%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%20%EC%8B%A4%EC%8A%B5/1.%20%EC%84%A0%ED%98%95_%EC%8B%9C%EC%8A%A4%ED%85%9C_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1번째 강의 실습

In [ ]:
import numpy as np

In [ ]:
# column vector

c = np.array([1,2,3]) # 1 dimesional array
print(c.shape)

print(c[0])# 1번째 엘리먼트

(3,)
1


In [ ]:
# row vector

r = np.array([[1, 2, 3]]) # row 값이 1로 고정된 벡터

print(r.shape)

(1, 3)


In [ ]:
# creating a matrix with all zeros
a = np.zeros((2, 2))
print(a, '\n')

# creating a matrix filled with the same constant같은 상수로 매트릭스를 만드는 법
c = np.full((2, 2), 7)
print(c, '\n')

# creating a matrix with random value
d = np.random.random((2, 2))# 0~1사이값
print(d)

[[0. 0.]
 [0. 0.]] 

[[7 7]
 [7 7]] 

[[0.20056007 0.37339795]
 [0.84228116 0.36643208]]


In [ ]:
# creating a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# creating another matrix

B = np.array([[11, 12, 13, 14], [15, 16, 17, 18]])
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [ ]:
# transpose a matrix

A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
# matrix - matrix multiplicatin
np.dot(A, B) # 행렬 연산도 해주지만 내적연산도 해줌

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [ ]:
# size should match = 사이즈는 같아야 합니다.

np.dot(B, A)

ValueError: ignored

In [ ]:
# coefficient matrix A and a vectir b
# 강의에 나온 기대 수명 관계식

A = np.array([[60, 5.5, 1], [65, 5.0, 0], [55, 6.0, 1]]) # 몸무게 흡연 여부 등등
B = np.array([66, 70, 78])# 타겟값


In [ ]:
# identity matrix

eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# computing an inverse
from numpy.linalg import inv # inverse matirx 계산, 역행렬 계산
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [ ]:
# wrong matrix multiplication

A * A_inv

# 아이덴티티 매트릭스가 안나옴, 원소곱이라서!

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [ ]:
A @ A_inv # indentity matrix

array([[ 1.0000000e+00,  0.0000000e+00, -4.4408921e-16],
       [ 8.8817842e-16,  1.0000000e+00, -8.8817842e-16],
       [-8.8817842e-16,  0.0000000e+00,  1.0000000e+00]])

In [ ]:
# solution of a linear system

x = A_inv.dot(B)

x
# 최종 솔루션 역행렬과 타겟 벡터를 행렬곱함


array([ -0.43478261,  19.65217391, -16.        ])

$Ax = B$

$A^{-1}Ax = A^{-1}B$

$x = A^{-1}B$

identity matrix와 x를 행렬곱하니 x가 나옴

In [ ]:
from numpy.linalg import solve

x = solve(A, B) # 역행렬 값을 구해서 직접 곱해줘 값을 도출해줌 x, 역행렬을 구하지않고 바로 풀어내는 것
x

array([ -0.43478261,  19.65217391, -16.        ])

역행렬을 구해서 곱하는 경우는 드뭅니다.

그렇게 했을 경우 오류 오차가 커집니다, 그렇기에 직접적으로 inverse를 구하지 않습니다.

inverse를 구하지않고 바로 풀어내는 것은 컴퓨터가 해석적으로 푸는 것이기에 오차가 적음!

사람이 직업 미분을 해석적으로하면 $\frac d {dx} x^3 = 3$이렇게 나오지만 수치 미분하면 오차가 나오는 그럼 느낌 

만약 

$Ax = b$ 에서 A = 3, b = 6이라면

> 해석적으로는 x가 2라는 것을 알 수 있지만 역행렬을 구하게 되면

$x = A^{-1}b$ 

A_inv = 나누기를 의미함 즉 $\frac 1 3$이라는건데

컴퓨터가 $\frac 1 3 = 0.33333...$ 이렇게 인식하기에 반올림해야 되므로 오차 발생!

작은 오차지만 그게 나비효과로 커짐!



cs 231n 넘파이 튜토리얼 해보기
https://cs231n.github.io/python-numpy-tutorial/

https://towardsdatascience.com/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c
